### ISSUE TITLE
problem with exporting simulation values with VI CSV export

### ISSUE THREAD

**Issue by ttsesm** [rgsouthall/vi-suite06#11]
I have the following simple scene:

![image](https://user-images.githubusercontent.com/10189018/95659470-dbcd9e00-0b10-11eb-86b1-f333efa62a58.png)

I have the terrain plane subdivided to multiple quad faces. If I set only the terrain or the cube as a `Light sensor` then the `VI CSV Export`  seems to export the values for all vertices correctly. If I select faces instead of vertices it seems that there is always one facet missing.

Now if I select vertices and set both the terrain and the cube as `Light sensor` then the output values for terrain are limited to the amount of vertices of the cube. Apparently to the smallest geometry of the scene. On the other hand if I select faces instead the output values are limited to the amount of the geometry with the less faces and always one facet missing.

**Comment by rgsouthall** [comment]
Thanks for the bug report. This should now be fixed in git.

**Comment by ttsesm** [comment]
Hi Ryan,
Thanks for the update, I confirm that your last commit solves the issue with the missing face. However, there is still the issue when there are multiple `Light sensor` surfaces.

In the console I am correctly getting the correct points to be considered (with the print that you added in the last commit):

```
Per faces
Cube:
6
[Vector((0.0, 0.0, 2.8133926391601562)), Vector((0.0, -1.0, 1.8133926391601562)), Vector((-1.0, 0.0, 1.8133926391601562)), Vector((0.0, 0.0, 0.8133925199508667)), Vector((1.0, 0.0, 1.8133926391601562)), Vector((0.0, 1.0, 1.8133926391601562))]

Terrain:
22
[Vector((7.445186614990234, 7.445186614990234, 0.0)), Vector((-2.4817287921905518, 7.445186614990234, 0.0)), Vector((-2.4817287921905518, -2.4817287921905518, 0.0)), Vector((7.445186614990234, -2.4817287921905518, 0.0)), Vector((2.4817287921905518, -2.4817287921905518, 0.0)), Vector((2.4817287921905518, -7.445186614990234, 0.0)), Vector((7.445186614990234, -7.445186614990234, 0.0)), Vector((-7.445186614990234, -2.4817287921905518, 0.0)), Vector((-7.445186614990234, -7.445186614990234, 0.0)), Vector((-2.4817287921905518, -7.445186614990234, 0.0)), Vector((-7.445186614990234, 7.445186614990234, 0.0)), Vector((-7.445186614990234, 2.4817287921905518, 0.0)), Vector((-2.4817287921905518, 2.4817287921905518, 0.0)), Vector((2.4817287921905518, 7.445186614990234, 0.0)), Vector((2.4817287921905518, 2.4817287921905518, 0.0)), Vector((7.445186614990234, 2.4817287921905518, 0.0))]
Info: Simulation is finished

Per vertices
Cube:
8
[Vector((1.0, 1.0, 2.8133926391601562)), Vector((1.0, 1.0, 0.8133925199508667)), Vector((1.0, -1.0, 2.8133926391601562)), Vector((1.0, -1.0, 0.8133925199508667)), Vector((-1.0, 1.0, 2.8133926391601562)), Vector((-1.0, 1.0, 0.8133925199508667)), Vector((-1.0, -1.0, 2.8133926391601562)), Vector((-1.0, -1.0, 0.8133925199508667))]

Terrain:
33
[Vector((-9.926915168762207, -9.926915168762207, 0.0)), Vector((9.926915168762207, -9.926915168762207, 0.0)), Vector((-9.926915168762207, 9.926915168762207, 0.0)), Vector((9.926915168762207, 9.926915168762207, 0.0)), Vector((-9.926915168762207, 0.0, 0.0)), Vector((0.0, -9.926915168762207, 0.0)), Vector((9.926915168762207, 0.0, 0.0)), Vector((0.0, 9.926915168762207, 0.0)), Vector((0.0, 0.0, 0.0)), Vector((-9.926915168762207, -4.9634575843811035, 0.0)), Vector((4.9634575843811035, -9.926915168762207, 0.0)), Vector((9.926915168762207, 4.9634575843811035, 0.0)), Vector((-4.9634575843811035, 9.926915168762207, 0.0)), Vector((-9.926915168762207, 4.9634575843811035, 0.0)), Vector((-4.9634575843811035, -9.926915168762207, 0.0)), Vector((9.926915168762207, -4.9634575843811035, 0.0)), Vector((4.9634575843811035, 9.926915168762207, 0.0)), Vector((0.0, 4.9634575843811035, 0.0)), Vector((0.0, -4.9634575843811035, 0.0)), Vector((-4.9634575843811035, 0.0, 0.0)), Vector((4.9634575843811035, 0.0, 0.0)), Vector((4.9634575843811035, -4.9634575843811035, 0.0)), Vector((-4.9634575843811035, -4.9634575843811035, 0.0)), Vector((-4.9634575843811035, 4.9634575843811035, 0.0)), Vector((4.9634575843811035, 4.9634575843811035, 0.0))]
Info: Simulation is finished
```

But then below you can see that the exported values in the csv files from the `VI CSV export` node are limited to 6 and 8 values respectively based on the smaller geometry in the scene which in my case is the cube:

Per faces:
![image](https://user-images.githubusercontent.com/10189018/95689242-db133580-0bfe-11eb-8251-eb491a1ad715.png)

here I would expect to have 22 values for the plane instead of just 6.

 Per vertices:
![image](https://user-images.githubusercontent.com/10189018/95689267-0bf36a80-0bff-11eb-9f59-ce55d53f3acc.png)

accordingly here I would expect 33 values for the plane instead of only 8.

I guess you might need to reformat the output structure, I think it would make more sense to concatenate the values row-wise instead of column-wise otherwise you will need to fill the empty cells with zeros or NaN's. Something like that should be sufficient:

![image](https://user-images.githubusercontent.com/10189018/95689508-cafc5580-0c00-11eb-97a6-7538a42d53ba.png)

what do you think?

**Comment by ttsesm** [comment]
Thanks Ryan, with your last commit it seems to work fine now. 

![image](https://user-images.githubusercontent.com/10189018/95780995-78806f00-0cbc-11eb-914f-9bdf566e4db7.png)

I would argue though, that it would be nicer I believe to have the values concatenated row-wise instead of column-wise so that to avoid having these empty space between the different surfaces and I guess it would easier for someone to read the file as a point cloud from a text editor considering that the first 3 columns is gonna be always the x, y, z coordinates.

![image](https://user-images.githubusercontent.com/10189018/95781114-ae255800-0cbc-11eb-93d8-aab2ad6d56ca.png)

but I do not know, you might have something else in your mind.

**Comment by ttsesm** [comment]
Hi @rgsouthall, 

Another thing that I would like to report is the following. When I export the values per faces from my scenes  I've noticed that the x,y,z coordinates for some faces are the same which from my understanding this shouldn't be happening. E.g.

![image](https://user-images.githubusercontent.com/10189018/96742122-d569dc80-13c2-11eb-96a0-d1ea23ad443b.png)

I believe the problem lies to the fact that you are using [`bmesh.faces[x].calc_center_bounds()`](https://github.com/rgsouthall/vi-suite06/blob/8ea8fb8134ae34e8b5fdeedc36ad110ce92978e3/livi_func.py#L414) instead of ` obj.data.polygons[x].center` so faces that are really close to each other give the same "center bound".

Check below where I manually check on these two faces:

```
>>> obj.matrix_world @ bm.faces[0].calc_center_bounds()
Vector((0.9973182678222656, 3.257697820663452, 2.7399981021881104))

>>> obj.matrix_world @ bm.faces[1].calc_center_bounds()
Vector((0.9973182678222656, 3.257697820663452, 2.7399981021881104))

>>> obj.matrix_world @ obj.data.polygons[0].center
Vector((0.5806541442871094, 3.4626996517181396, 2.7399981021881104))

>>> obj.matrix_world @ obj.data.polygons[1].center
Vector((1.4139862060546875, 3.0526998043060303, 2.7399981021881104))
```

You can clearly see that using the `calc_center_bound()` returns the same output for both faces while their actual position in the space differs.
