### ISSUE TITLE
AttributeError: 'VI_Params_Scene' object has no attribute 'vi_scatt_col'

### ISSUE THREAD

**Issue by distruccion** [rgsouthall/vi-suite06#36]
In Blender 4.2, on Windows, when using the wind rose node, the following error occurs:

Error: Python: Traceback (most recent call last):
  File "...\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\vi-suite07-vi-suite07_beta6\vi_operators.py", line 294, in invoke
    ax.bar(vawd, vad, bins=sbinvals, normed=True, opening=0.8, edgecolor='white', cmap=mcm.get_cmap(svp.vi_scatt_col))
                                                                                                    ^^^^^^^^^^^^^^^^
AttributeError: 'VI_Params_Scene' object has no attribute 'vi_scatt_col'
rna_uiItemR: property not found: VI_Params_Scene.vi_scatt_col

**Comment by rgsouthall** [comment]
Thanks for the bug report.
This should now be fixed in the beta 6 code. You just need to replace the __init__.py and vi_display.py files.
